#!/usr/bin/env python3
"""Self-host the webfonts instead of loading them from Google.

    python3 brand/fetch-fonts.py

Downloads the latin variable woff2 for each family, subsets it to the characters
this site can actually render, and writes assets/fonts/fonts.css with matching
@font-face rules.

Why self-host: a <link> to fonts.googleapis.com is render-blocking and costs two
extra DNS + TLS handshakes before a single word appears, on every page load.
Same-origin fonts remove that, and they keep working offline.

Why variable + subset: seven static weights from Google total ~290 KB. Two
variable fonts covering the same weight ranges, subsetted to the ranges below,
total 61 KB — with no visible difference and every intermediate weight available.

Needs: python3 -m pip install --user fonttools brotli
Archivo and Inter are both SIL Open Font License 1.1, which permits this.
"""
import os
import re
import subprocess
import sys
import tempfile
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "assets", "fonts")

# Variable fonts: one file per family covers the whole weight range, instead of
# one static file per weight. Two downloads rather than seven, and any weight in
# the range becomes available for free.
FAMILIES = {
    "Archivo": (600, 800),   # 600 nav, 700 buttons/labels, 800 headings
    "Inter": (400, 700),     # 400 body, 500/600 labels, 700 strong
}

# Generous but bounded: ASCII, Latin-1 (Spanish accents, ¿ ¡ ñ ü, © · ×),
# general punctuation (curly quotes, en/em dash, ellipsis), arrows, ★, €, ™.
# Wider than the 85 characters in use today so copy edits don't break glyphs.
UNICODES = "U+0020-007F,U+00A0-00FF,U+0131,U+0152-0153,U+2000-206F,U+2190-2193,U+2212,U+2605,U+20AC,U+2122"

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    try:
        import fontTools  # noqa: F401
        import brotli     # noqa: F401
    except ImportError:
        sys.exit("Needs fonttools + brotli:\n"
                 "  python3 -m pip install --user fonttools brotli")

    os.makedirs(OUT, exist_ok=True)
    for stale in os.listdir(OUT):                    # drop previous output
        if stale.endswith((".woff2", ".css")):
            os.remove(os.path.join(OUT, stale))

    spec = "&".join(
        "family=%s:wght@%d..%d" % (fam, lo, hi)
        for fam, (lo, hi) in FAMILIES.items()
    )
    css = fetch("https://fonts.googleapis.com/css2?%s&display=swap" % spec)

    # Google's CSS is a run of "/* subset */ @font-face {...}" blocks. We take
    # only 'latin' — 'latin-ext' is Eastern European and unused here (Spanish
    # accented characters live in 'latin').
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)

    rules, before, after = [], 0, 0
    for subset, block in blocks:
        if subset != "latin":
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip()
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        raw = fetch(url, binary=True)
        before += len(raw)
        name = "%s-var.woff2" % family.lower().replace(" ", "-")
        path = os.path.join(OUT, name)

        with tempfile.NamedTemporaryFile(suffix=".woff2", delete=False) as tmp:
            tmp.write(raw)
            tmp_path = tmp.name
        try:
            subprocess.run(
                [sys.executable, "-m", "fontTools.subset", tmp_path,
                 "--unicodes=" + UNICODES,
                 "--layout-features=kern,liga,calt",
                 "--drop-tables+=DSIG",
                 "--flavor=woff2", "--output-file=" + path],
                check=True, capture_output=True,
            )
        finally:
            os.unlink(tmp_path)

        size = os.path.getsize(path)
        after += size
        print("  %-20s %6.1f KB  (from %5.1f KB)  weights %s" % (name, size / 1024, len(raw) / 1024, weight))

        rules.append(
            "@font-face {\n"
            "  font-family: '%s';\n"
            "  font-style: normal;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            "  src: url('/assets/fonts/%s') format('woff2');\n"
            "}" % (family, weight, name)
        )

    header = (
        "/* Self-hosted, subsetted webfonts — generated by brand/fetch-fonts.py.\n"
        "   Do not edit; re-run the script instead.\n"
        "   Archivo and Inter, SIL Open Font License 1.1. */\n\n"
    )
    with open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write(header + "\n\n".join(rules) + "\n")

    print("\n%d faces: %.1f KB subsetted, down from %.1f KB (%.0f%% smaller)"
          % (len(rules), after / 1024, before / 1024, 100 * (1 - after / before)))


if __name__ == "__main__":
    main()
